/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

/*
 Copyright (C) 2016 Eric Ehlers

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <quantlib-dev@lists.sf.net>. The license is also available online at
 <http://quantlib.org/license.shtml>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

//#if defined(HAVE_CONFIG_H)     // Dynamically created by configure
//    #include <qlo/config.hpp>
//#endif
#include <qlo/conversions/all.hpp>
#include <qlo/objects/objmanual_termstructures.hpp>
#include <qlo/objects/objmanual_quotes.hpp>
#include <ql/utilities/dataparsers.hpp>
#include <ql/time/period.hpp>
#include <ql/quotes/all.hpp>
#include <boost/algorithm/string/case_conv.hpp>

namespace QuantLib {
    class Quote;
    class SimpleQuote;
    class FuturesConvAdjustmentQuote;
    class LastFixingQuote;
    class TermStructure;
    class DefaultProbabilityTermStructure;
}

QuantLib::Period QuantLibAddin::Get<std::string, QuantLib::Period>::operator()(const std::string &in) {
    // This was the functionality in the old build:
    //ret = QuantLib::PeriodParser::parse(in);
    //ret.normalize();
    // In the old build the functionality below was found in the ctor of QuantLibAddin::Euribor.
    // Now we use it here for all autogenerated conversions, is that correct?
    QuantLib::Period ret;
    std::string p = boost::algorithm::to_upper_copy(in);
    if ("SW"==p)
        ret = 1*QuantLib::Weeks;
    else {
        ret = QuantLib::PeriodParser::parse(p);
        ret.normalize();
    }
    return ret;
}

template <class QuantLibAddinQuote, class QuantLibQuote>
boost::shared_ptr<QuantLibQuote> QuantLibAddin::getQuote(const std::string &in) {
    RP_GET_OBJECT(objectId, in, reposit::Object)
    return QuantLibAddin::CoerceQuote<QuantLibAddinQuote, QuantLibQuote>()(objectId);
}

template boost::shared_ptr<QuantLib::SimpleQuote>
QuantLibAddin::getQuote<QuantLibAddin::SimpleQuote, QuantLib::SimpleQuote>(const std::string &);

template boost::shared_ptr<QuantLib::FuturesConvAdjustmentQuote>
QuantLibAddin::getQuote<QuantLibAddin::FuturesConvAdjustmentQuote, QuantLib::FuturesConvAdjustmentQuote>(const std::string &);

template boost::shared_ptr<QuantLib::LastFixingQuote>
QuantLibAddin::getQuote<QuantLibAddin::LastFixingQuote, QuantLib::LastFixingQuote>(const std::string &);

template <class QuantLibAddinYts, class QuantLibYts>
boost::shared_ptr<QuantLibYts> QuantLibAddin::getYieldTermStructure(const std::string &in) {
    RP_GET_OBJECT(objectID, in, reposit::Object)
    return QuantLibAddin::CoerceTermStructure<QuantLibAddinYts, QuantLibYts>()(objectID);
}

template boost::shared_ptr<QuantLib::TermStructure>
QuantLibAddin::getYieldTermStructure<QuantLibAddin::TermStructure, QuantLib::TermStructure>(const std::string&);

template boost::shared_ptr<QuantLib::YieldTermStructure>
QuantLibAddin::getYieldTermStructure<QuantLibAddin::YieldTermStructure, QuantLib::YieldTermStructure>(const std::string&);

template boost::shared_ptr<QuantLib::DefaultProbabilityTermStructure>
QuantLibAddin::getYieldTermStructure<QuantLibAddin::DefaultProbabilityTermStructure, QuantLib::DefaultProbabilityTermStructure>(const std::string&);

//QuantLib::Handle<QuantLib::YieldTermStructure>
//QuantLibAddin::Get<std::string, QuantLib::Handle<QuantLib::YieldTermStructure> >::operator()(
//    const std::string &in,
//    const QuantLib::Handle<QuantLib::YieldTermStructure> &defaultValue) {
//    RP_GET_OBJECT_DEFAULT(objectId, in, reposit::Object)
//    return QuantLibAddin::CoerceHandle<
//        QuantLibAddin::YieldTermStructure,
//        QuantLib::YieldTermStructure>()(
//            objectId, defaultValue);
//}

QuantLib::Handle<QuantLib::YieldTermStructure> QuantLibAddin::getYieldTermStructureHandle(
    const std::string &in) {
    RP_GET_OBJECT(objectId, in, reposit::Object)
    return QuantLibAddin::CoerceHandle<QuantLibAddin::YieldTermStructure, QuantLib::YieldTermStructure>()(objectId);            
}

QuantLib::Handle<QuantLib::YieldTermStructure> QuantLibAddin::getYieldTermStructureHandle(
    const std::string &in,
    const QuantLib::Handle<QuantLib::YieldTermStructure> &defaultValue) {
    RP_GET_OBJECT_DEFAULT(objectId, in, reposit::Object)
    return QuantLibAddin::CoerceHandle<QuantLibAddin::YieldTermStructure, QuantLib::YieldTermStructure>()(objectId, defaultValue);            
}
