/* -*- mode: c++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*- */

/*
 Copyright (C) 2016 Eric Ehlers

 This file is part of QuantLib, a free-software/open-source library
 for financial quantitative analysts and developers - http://quantlib.org/

 QuantLib is free software: you can redistribute it and/or modify it
 under the terms of the QuantLib license.  You should have received a
 copy of the license along with this program; if not, please email
 <quantlib-dev@lists.sf.net>. The license is also available online at
 <http://quantlib.org/license.shtml>.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the license for more details.
*/

//#if defined(HAVE_CONFIG_H)     // Dynamically created by configure
//    #include <qlo/config.hpp>
//#endif
#include <qlo/conversions/get.hpp>
#include <qlo/conversions/coercehandle.hpp>
#include <qlo/objects/objmanual_termstructures.hpp>
#include <ql/utilities/dataparsers.hpp>
#include <ql/time/period.hpp>
#include <boost/algorithm/string/case_conv.hpp>

QuantLib::Period QuantLibAddin::Get<std::string, QuantLib::Period>::operator()(const std::string &in) {
    // This was the functionality in the old build:
    //ret = QuantLib::PeriodParser::parse(in);
    //ret.normalize();
    // In the old build the functionality below was found in the ctor of QuantLibAddin::Euribor.
    // Now we use it here for all autogenerated conversions, is that correct?
    QuantLib::Period ret;
    std::string p = boost::algorithm::to_upper_copy(in);
    if ("SW"==p)
        ret = 1*QuantLib::Weeks;
    else {
        ret = QuantLib::PeriodParser::parse(p);
        ret.normalize();
    }
    return ret;
}

//QuantLib::Handle<QuantLib::Quote> QuantLibAddin::Get<std::string, QuantLib::Handle<QuantLib::Quote> >::operator()(const std::string &in) {
//}

QuantLib::Handle<QuantLib::YieldTermStructure>
QuantLibAddin::Get<std::string, QuantLib::Handle<QuantLib::YieldTermStructure> >::operator()(
    const std::string &in,
    const QuantLib::Handle<QuantLib::YieldTermStructure> &defaultValue) {
    RP_GET_OBJECT_DEFAULT(x, in, reposit::Object)
    return QuantLibAddin::CoerceHandle<
        QuantLibAddin::YieldTermStructure,
        QuantLib::YieldTermStructure>()(
            x, defaultValue);
}
